### ISSUE TITLE
Propuesta de charlas

### ISSUE THREAD

**Issue by eafelix** [popayanjs/Bienvenido#2]
Chicos queria proponerles si alguno se anima a dar una charla de node webkit, ya que vemos desde Arg que esta tomando mucho impulso para aplicaciones. Les puedo pasar info o slides para el que se anime a ver el tema !

**Comment by hcamilogruiz** [comment]
Viejo @eafelix me sumo a esa propuesta. Quedo atento a los slides. Gracias. Abrazo.!
