### ISSUE TITLE
Workshops

### ISSUE THREAD

**Issue by alejandronanez** [popayanjs/Bienvenido#3]
Gente qué tal abrir un workshop para crear algo con Javascript de ceros, puede ser enfocado a enseñar las bases?

Escucho ideas ;) @hcamilogruiz @alexchanapp

**Comment by hcamilogruiz** [comment]
Interesante propuesta @alejandronanez podemos organizar algo básico e ir profundizando en los temas.! Tenemos este espacio en CodeAcademy para tomar ejemplos y seguirlos: http://www.codecademy.com/es/tracks/javascript-traduccion-al-espanol-america-latina-clone

Quedo atento,
Gracias.

**Comment by eafelix** [comment]
Chicos tienen los workshop de nodeschool: 
http://nodeschool.io/es/ 

Están geniales para enseñar tanto a programar a gente de 0, como enseñar Node o javascript a programadores.  
A nuestros alumnos en el instituto donde enseño JS usamos los workshops , como tambien los use para especializarme mas en Node.
Porque no un nodeschool en popayan :P

**Comment by alexchanapp** [comment]
Viejo Alejo y amigos! Gusto en volver a escucharlos.
He estado un poco perdido por cuestiones laborales, pero tu idea Alejo me parece genial.
De hecho al equipo y en tu meetup había propuesto algo así, pero no lo hemos concretado.
Te propongo algo y reenvío esta conversación a todo el equipo.
Programemos un hangout para los próximos días y hablamos del asunto entre todos. Me gustaría que escucharamos propuestas, opiniones, sugerencias, aportes, ideas, etc para el desarrollo de la actividad. Y tomar la idea de @eafelix que me parece genial tmb! De hecho he estado pensando en algo así como el instituto del que habla @eafelix... en la charla les cuento.

Me avisan para cuando podemos programar el hg.

Saludos!

**Comment by alejandronanez** [comment]
@hcamilogruiz @eafelix @alexchanapp Perfecto. Yo puedo todos los días desde las 6:00pm hasta las 8:30pm GMT-5.

**Comment by eafelix** [comment]
Los workshops de nodeschool son gratuitos, y están pensados para los eventos nodechool. 
Invitan gente con sus notebooks e instalan los workshops (que son tutoriales auto-guiados) y si alguno se demora o tiene problemas con algún ejercicio tienen tutores para ayudarlos (gente con experiencia en node). 

Los PPT se los podemos pedir a @a0viedo para la presentación de los workshop.

**Comment by a0viedo** [comment]
Por supuesto, todos los slides que pueden encontrar [acá](https://slides.com/a0viedo/) son forkeables, ajusten/cambien lo que ustedes sientan necesario.

Recuerden que [javascripting](https://github.com/sethvincent/javascripting) y [learnyounode](https://github.com/workshopper/learnyounode) están traducidos al español.

**Comment by alexchanapp** [comment]
Amigos míos
Podemos programar para mañana sábado? O para la próxima semana, que día?

Me cuentan!

**Comment by alexchanapp** [comment]
Amigos míos
Podemos programar para mañana sábado? O para la próxima semana, que día?

Me cuentan!

**Comment by alejandronanez** [comment]
@alexchanapp apenas veo el mensaje :/. Quedo atento cuando digan, yo puedo todos los días desde las 6:00pm hasta las 8:30pm GMT-5.
